/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Laxcor
 */
public class AppointmentView extends javax.swing.JPanel {

    private String name;
    private String room;
    private String time;
    
    /**
     * Creates new form AppointmentView
     */
    public AppointmentView(String name, String room, String time) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        appointmentName = new javax.swing.JLabel();
        alarmIcon = new javax.swing.JLabel();
        appointmentTime = new javax.swing.JLabel();
        appointmentRoom = new javax.swing.JLabel();
        appointmentStatus = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(112, 38));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        appointmentName.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        appointmentName.setText("<Name>");
        add(appointmentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        alarmIcon.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        alarmIcon.setText("---");
        add(alarmIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, -1));

        appointmentTime.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        appointmentTime.setText("<Timestamp>");
        add(appointmentTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        appointmentRoom.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        appointmentRoom.setText("<Room nr.>");
        add(appointmentRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        appointmentStatus.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        appointmentStatus.setText("---");
        add(appointmentStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alarmIcon;
    private javax.swing.JLabel appointmentName;
    private javax.swing.JLabel appointmentRoom;
    private javax.swing.JLabel appointmentStatus;
    private javax.swing.JLabel appointmentTime;
    // End of variables declaration//GEN-END:variables
}
