/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import client.Alarm;
import client.Converters;
import client.Group;
import client.Main;
import client.Meeting;
import client.Notification;
import client.Person;
import client.Room;
import java.sql.Time;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author Laxcor
 */
public class MainWindow extends javax.swing.JFrame {
    
    private Main main;
    
    private int currentWeek;
    private int maximumWeek;
    private DefaultListModel<Notification> notifications;
    private DefaultComboBoxModel<Integer> weekSelectionModel;
    private GregorianCalendar defaultCalendar;
    private GregorianCalendar currentCalendar;
    private ArrayList<AppointmentView> appointments;
    private ArrayList<JPanel> dayPanels;
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form MainWindow
     */
    public MainWindow() {}
    public MainWindow(Main main) {
        
        
        //Setting the main and person objects
        this.main = main;
        //Setting the fram to a maximized state
        setExtendedState(getExtendedState() | JFrame.MAXIMIZED_BOTH);
        //NetBeans component init
        initComponents();
        
        appointments = new ArrayList<>();
        
        
        this.main.setFrame(this);
        
        notifications = new DefaultListModel<>();
        weekSelectionModel = new DefaultComboBoxModel<>();
        
        currentCalendar = new GregorianCalendar();
        currentCalendar.setFirstDayOfWeek(Calendar.MONDAY);
        
        dayPanels = new ArrayList<>();
        dayPanels.add(mondayPanel);
        dayPanels.add(tuesdayPanel);
        dayPanels.add(wednesdayPanel);
        dayPanels.add(thursdayPanel);
        dayPanels.add(fridayPanel);
        dayPanels.add(saturdayPanel);
        dayPanels.add(sundayPanel);
        
        //Fixing general component placement and size
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                revalidate();
            }
        });
        informationPanel.setVisible(false);
        usernameLabel.setText(this.main.getPersonName());
        defaultCalendar = new GregorianCalendar();
        defaultCalendar.setFirstDayOfWeek(Calendar.MONDAY);
        currentWeek = defaultCalendar.get(Calendar.WEEK_OF_YEAR);
        maximumWeek = defaultCalendar.getActualMaximum(Calendar.WEEK_OF_YEAR);
        weekNumberLabel.setText(currentWeek + "");
        populateWeekSelectionModel();
        skipToWeekBox.setModel(weekSelectionModel);
        skipToWeekBox.setSelectedIndex(currentWeek - 1);
        notificationList.setModel(notifications);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        welcomeLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        topPanel = new javax.swing.JPanel();
        weekLabel = new javax.swing.JLabel();
        weekNumberLabel = new javax.swing.JLabel();
        previousWeekButton = new javax.swing.JButton();
        nextWeekButton = new javax.swing.JButton();
        sidePanel = new javax.swing.JPanel();
        newAppointmentButton = new javax.swing.JButton();
        skipToWeekLabel = new javax.swing.JLabel();
        skipToWeekBox = new javax.swing.JComboBox();
        otherCalendarLabel = new javax.swing.JLabel();
        separator1 = new javax.swing.JSeparator();
        otherPersonBox = new javax.swing.JComboBox();
        addOtherPersonButton = new javax.swing.JButton();
        separator2 = new javax.swing.JSeparator();
        notificationsLable = new javax.swing.JLabel();
        notificationScroll = new javax.swing.JScrollPane();
        notificationList = new javax.swing.JList();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        centerPanel = new javax.swing.JPanel();
        calendarScrollPane = new javax.swing.JScrollPane();
        calendarPanel = new javax.swing.JPanel();
        timestampPanel = new javax.swing.JPanel();
        timestamp0 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        timestamp1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        timestamp2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        timestamp3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        timestamp4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        timestamp5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        timestamp6 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        timestamp7 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        timestamp8 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        timestamp9 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        timestamp10 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        timestamp11 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        timestamp12 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        timestamp13 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        timestamp14 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        timestamp15 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        timestamp16 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        timestamp17 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        timestamp18 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        timestamp19 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        timestamp20 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        timestamp21 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        timestamp22 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        timestamp23 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        mondayPanel = new javax.swing.JPanel();
        tuesdayPanel = new javax.swing.JPanel();
        wednesdayPanel = new javax.swing.JPanel();
        thursdayPanel = new javax.swing.JPanel();
        fridayPanel = new javax.swing.JPanel();
        saturdayPanel = new javax.swing.JPanel();
        sundayPanel = new javax.swing.JPanel();
        dayAndDatePanel = new javax.swing.JPanel();
        fillerPanel = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        informationPanel = new gui.InformationPanel(this);
        needSpace = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logoPanel.setBackground(new java.awt.Color(230, 230, 230));

        logoLabel.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logo felles.png"))); // NOI18N

        welcomeLabel.setText("Welcome, ");

        usernameLabel.setText("<<INSERT USERNAME>>");

        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout logoPanelLayout = new javax.swing.GroupLayout(logoPanel);
        logoPanel.setLayout(logoPanelLayout);
        logoPanelLayout.setHorizontalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1))
            .addGroup(logoPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(welcomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usernameLabel)
                .addContainerGap())
            .addGroup(logoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        logoPanelLayout.setVerticalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoPanelLayout.createSequentialGroup()
                .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcomeLabel)
                    .addComponent(usernameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        topPanel.setBackground(new java.awt.Color(230, 230, 230));

        weekLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        weekLabel.setText("Week");

        weekNumberLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        weekNumberLabel.setText("10");

        previousWeekButton.setText("<");
        previousWeekButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousWeekButtonActionPerformed(evt);
            }
        });

        nextWeekButton.setText(">");
        nextWeekButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextWeekButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(previousWeekButton)
                .addGap(18, 18, 18)
                .addComponent(weekLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(weekNumberLabel)
                .addGap(18, 18, 18)
                .addComponent(nextWeekButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(weekLabel)
                            .addComponent(weekNumberLabel)))
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(previousWeekButton))
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(nextWeekButton)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        sidePanel.setBackground(new java.awt.Color(230, 230, 230));

        newAppointmentButton.setText("Create new appointment");
        newAppointmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAppointmentButtonActionPerformed(evt);
            }
        });

        skipToWeekLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        skipToWeekLabel.setText(" Skip to week");

        skipToWeekBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53" }));
        skipToWeekBox.setSelectedIndex(9);
        skipToWeekBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skipToWeekBoxActionPerformed(evt);
            }
        });

        otherCalendarLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        otherCalendarLabel.setText("Other calendars");

        otherPersonBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Demarcus Hose", "Antionette Hunsberger", "Ariana Vanek", "Hunter Isler", "Mackenzie Ronning", "Davina Goldblatt", "Flavia Shell", "Geneva Claybrooks", "Matthew Gough", "Brooks Tyson", "Inez Sweet", "Luetta Galasso", "Lesha Vicari", "Minta Beyer", "Bonny Barley", "Reatha Taber", "Gerri Carasco", "Rebeca Benda", "Kenton Aponte", "Sabina Hover" }));

        addOtherPersonButton.setText("Add");

        notificationsLable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        notificationsLable.setText("Notifications");

        notificationList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        notificationList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                notificationListValueChanged(evt);
            }
        });
        notificationScroll.setViewportView(notificationList);

        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newAppointmentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addComponent(skipToWeekLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(skipToWeekBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(separator1)
                    .addComponent(separator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(notificationScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(otherCalendarLabel)
                            .addComponent(notificationsLable)
                            .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(sidePanelLayout.createSequentialGroup()
                                    .addComponent(otherPersonBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(addOtherPersonButton))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newAppointmentButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(skipToWeekLabel)
                    .addComponent(skipToWeekBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(otherCalendarLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(otherPersonBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addOtherPersonButton))
                .addGap(12, 12, 12)
                .addComponent(separator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(notificationsLable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(notificationScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addContainerGap())
        );

        centerPanel.setBackground(new java.awt.Color(230, 230, 230));

        calendarScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        calendarScrollPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                calendarScrollPaneMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                calendarScrollPaneMouseReleased(evt);
            }
        });

        calendarPanel.setPreferredSize(new java.awt.Dimension(849, 914));
        calendarPanel.setLayout(new java.awt.GridLayout(1, 7));

        timestampPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        timestampPanel.setLayout(new java.awt.GridLayout(24, 1));

        timestamp0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel15.setText("00:00");

        javax.swing.GroupLayout timestamp0Layout = new javax.swing.GroupLayout(timestamp0);
        timestamp0.setLayout(timestamp0Layout);
        timestamp0Layout.setHorizontalGroup(
            timestamp0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timestamp0Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        timestamp0Layout.setVerticalGroup(
            timestamp0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timestamp0Layout.createSequentialGroup()
                .addComponent(jLabel15)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        timestampPanel.add(timestamp0);

        timestamp1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel16.setText("01:00");

        javax.swing.GroupLayout timestamp1Layout = new javax.swing.GroupLayout(timestamp1);
        timestamp1.setLayout(timestamp1Layout);
        timestamp1Layout.setHorizontalGroup(
            timestamp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timestamp1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        timestamp1Layout.setVerticalGroup(
            timestamp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timestamp1Layout.createSequentialGroup()
                .addComponent(jLabel16)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        timestampPanel.add(timestamp1);

        timestamp2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel17.setText("02:00");

        javax.swing.GroupLayout timestamp2Layout = new javax.swing.GroupLayout(timestamp2);
        timestamp2.setLayout(timestamp2Layout);
        timestamp2Layout.setHorizontalGroup(
            timestamp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timestamp2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        timestamp2Layout.setVerticalGroup(
            timestamp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timestamp2Layout.createSequentialGroup()
                .addComponent(jLabel17)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        timestampPanel.add(timestamp2);

        timestamp3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel19.setText("03:00");

        javax.swing.GroupLayout timestamp3Layout = new javax.swing.GroupLayout(timestamp3);
        timestamp3.setLayout(timestamp3Layout);
        timestamp3Layout.setHorizontalGroup(
            timestamp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timestamp3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        timestamp3Layout.setVerticalGroup(
            timestamp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timestamp3Layout.createSequentialGroup()
                .addComponent(jLabel19)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        timestampPanel.add(timestamp3);

        timestamp4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel18.setText("04:00");

        javax.swing.GroupLayout timestamp4Layout = new javax.swing.GroupLayout(timestamp4);
        timestamp4.setLayout(timestamp4Layout);
        timestamp4Layout.setHorizontalGroup(
            timestamp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timestamp4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        timestamp4Layout.setVerticalGroup(
            timestamp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timestamp4Layout.createSequentialGroup()
                .addComponent(jLabel18)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        timestampPanel.add(timestamp4);

        timestamp5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel20.setText("05:00");

        javax.swing.GroupLayout timestamp5Layout = new javax.swing.GroupLayout(timestamp5);
        timestamp5.setLayout(timestamp5Layout);
        timestamp5Layout.setHorizontalGroup(
            timestamp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timestamp5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        timestamp5Layout.setVerticalGroup(
            timestamp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timestamp5Layout.createSequentialGroup()
                .addComponent(jLabel20)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        timestampPanel.add(timestamp5);

        timestamp6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel21.setText("06:00");

        javax.swing.GroupLayout timestamp6Layout = new javax.swing.GroupLayout(timestamp6);
        timestamp6.setLayout(timestamp6Layout);
        timestamp6Layout.setHorizontalGroup(
            timestamp6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timestamp6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        timestamp6Layout.setVerticalGroup(
            timestamp6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timestamp6Layout.createSequentialGroup()
                .addComponent(jLabel21)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        timestampPanel.add(timestamp6);

        timestamp7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel22.setText("07:00");

        javax.swing.GroupLayout timestamp7Layout = new javax.swing.GroupLayout(timestamp7);
        timestamp7.setLayout(timestamp7Layout);
        timestamp7Layout.setHorizontalGroup(
            timestamp7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timestamp7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        timestamp7Layout.setVerticalGroup(
            timestamp7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timestamp7Layout.createSequentialGroup()
                .addComponent(jLabel22)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        timestampPanel.add(timestamp7);

        timestamp8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel23.setText("08:00");

        javax.swing.GroupLayout timestamp8Layout = new javax.swing.GroupLayout(timestamp8);
        timestamp8.setLayout(timestamp8Layout);
        timestamp8Layout.setHorizontalGroup(
            timestamp8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timestamp8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        timestamp8Layout.setVerticalGroup(
            timestamp8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timestamp8Layout.createSequentialGroup()
                .addComponent(jLabel23)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        timestampPanel.add(timestamp8);

        timestamp9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel24.setText("09:00");

        javax.swing.GroupLayout timestamp9Layout = new javax.swing.GroupLayout(timestamp9);
        timestamp9.setLayout(timestamp9Layout);
        timestamp9Layout.setHorizontalGroup(
            timestamp9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timestamp9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        timestamp9Layout.setVerticalGroup(
            timestamp9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timestamp9Layout.createSequentialGroup()
                .addComponent(jLabel24)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        timestampPanel.add(timestamp9);

        timestamp10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel25.setText("10:00");

        javax.swing.GroupLayout timestamp10Layout = new javax.swing.GroupLayout(timestamp10);
        timestamp10.setLayout(timestamp10Layout);
        timestamp10Layout.setHorizontalGroup(
            timestamp10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timestamp10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        timestamp10Layout.setVerticalGroup(
            timestamp10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timestamp10Layout.createSequentialGroup()
                .addComponent(jLabel25)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        timestampPanel.add(timestamp10);

        timestamp11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel26.setText("11:00");

        javax.swing.GroupLayout timestamp11Layout = new javax.swing.GroupLayout(timestamp11);
        timestamp11.setLayout(timestamp11Layout);
        timestamp11Layout.setHorizontalGroup(
            timestamp11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timestamp11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        timestamp11Layout.setVerticalGroup(
            timestamp11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timestamp11Layout.createSequentialGroup()
                .addComponent(jLabel26)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        timestampPanel.add(timestamp11);

        timestamp12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel27.setText("12:00");

        javax.swing.GroupLayout timestamp12Layout = new javax.swing.GroupLayout(timestamp12);
        timestamp12.setLayout(timestamp12Layout);
        timestamp12Layout.setHorizontalGroup(
            timestamp12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timestamp12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        timestamp12Layout.setVerticalGroup(
            timestamp12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timestamp12Layout.createSequentialGroup()
                .addComponent(jLabel27)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        timestampPanel.add(timestamp12);

        timestamp13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel28.setText("13:00");

        javax.swing.GroupLayout timestamp13Layout = new javax.swing.GroupLayout(timestamp13);
        timestamp13.setLayout(timestamp13Layout);
        timestamp13Layout.setHorizontalGroup(
            timestamp13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timestamp13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        timestamp13Layout.setVerticalGroup(
            timestamp13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timestamp13Layout.createSequentialGroup()
                .addComponent(jLabel28)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        timestampPanel.add(timestamp13);

        timestamp14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel29.setText("14:00");

        javax.swing.GroupLayout timestamp14Layout = new javax.swing.GroupLayout(timestamp14);
        timestamp14.setLayout(timestamp14Layout);
        timestamp14Layout.setHorizontalGroup(
            timestamp14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timestamp14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        timestamp14Layout.setVerticalGroup(
            timestamp14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timestamp14Layout.createSequentialGroup()
                .addComponent(jLabel29)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        timestampPanel.add(timestamp14);

        timestamp15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel30.setText("15:00");

        javax.swing.GroupLayout timestamp15Layout = new javax.swing.GroupLayout(timestamp15);
        timestamp15.setLayout(timestamp15Layout);
        timestamp15Layout.setHorizontalGroup(
            timestamp15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timestamp15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        timestamp15Layout.setVerticalGroup(
            timestamp15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timestamp15Layout.createSequentialGroup()
                .addComponent(jLabel30)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        timestampPanel.add(timestamp15);

        timestamp16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel31.setText("16:00");

        javax.swing.GroupLayout timestamp16Layout = new javax.swing.GroupLayout(timestamp16);
        timestamp16.setLayout(timestamp16Layout);
        timestamp16Layout.setHorizontalGroup(
            timestamp16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timestamp16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        timestamp16Layout.setVerticalGroup(
            timestamp16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timestamp16Layout.createSequentialGroup()
                .addComponent(jLabel31)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        timestampPanel.add(timestamp16);

        timestamp17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel32.setText("17:00");

        javax.swing.GroupLayout timestamp17Layout = new javax.swing.GroupLayout(timestamp17);
        timestamp17.setLayout(timestamp17Layout);
        timestamp17Layout.setHorizontalGroup(
            timestamp17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timestamp17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        timestamp17Layout.setVerticalGroup(
            timestamp17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timestamp17Layout.createSequentialGroup()
                .addComponent(jLabel32)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        timestampPanel.add(timestamp17);

        timestamp18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel33.setText("18:00");

        javax.swing.GroupLayout timestamp18Layout = new javax.swing.GroupLayout(timestamp18);
        timestamp18.setLayout(timestamp18Layout);
        timestamp18Layout.setHorizontalGroup(
            timestamp18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timestamp18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        timestamp18Layout.setVerticalGroup(
            timestamp18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timestamp18Layout.createSequentialGroup()
                .addComponent(jLabel33)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        timestampPanel.add(timestamp18);

        timestamp19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel34.setText("19:00");

        javax.swing.GroupLayout timestamp19Layout = new javax.swing.GroupLayout(timestamp19);
        timestamp19.setLayout(timestamp19Layout);
        timestamp19Layout.setHorizontalGroup(
            timestamp19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timestamp19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel34)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        timestamp19Layout.setVerticalGroup(
            timestamp19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timestamp19Layout.createSequentialGroup()
                .addComponent(jLabel34)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        timestampPanel.add(timestamp19);

        timestamp20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel35.setText("20:00");

        javax.swing.GroupLayout timestamp20Layout = new javax.swing.GroupLayout(timestamp20);
        timestamp20.setLayout(timestamp20Layout);
        timestamp20Layout.setHorizontalGroup(
            timestamp20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timestamp20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        timestamp20Layout.setVerticalGroup(
            timestamp20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timestamp20Layout.createSequentialGroup()
                .addComponent(jLabel35)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        timestampPanel.add(timestamp20);

        timestamp21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel36.setText("21:00");

        javax.swing.GroupLayout timestamp21Layout = new javax.swing.GroupLayout(timestamp21);
        timestamp21.setLayout(timestamp21Layout);
        timestamp21Layout.setHorizontalGroup(
            timestamp21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timestamp21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel36)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        timestamp21Layout.setVerticalGroup(
            timestamp21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timestamp21Layout.createSequentialGroup()
                .addComponent(jLabel36)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        timestampPanel.add(timestamp21);

        timestamp22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel37.setText("22:00");

        javax.swing.GroupLayout timestamp22Layout = new javax.swing.GroupLayout(timestamp22);
        timestamp22.setLayout(timestamp22Layout);
        timestamp22Layout.setHorizontalGroup(
            timestamp22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timestamp22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel37)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        timestamp22Layout.setVerticalGroup(
            timestamp22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timestamp22Layout.createSequentialGroup()
                .addComponent(jLabel37)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        timestampPanel.add(timestamp22);

        timestamp23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel38.setText("23:00");

        javax.swing.GroupLayout timestamp23Layout = new javax.swing.GroupLayout(timestamp23);
        timestamp23.setLayout(timestamp23Layout);
        timestamp23Layout.setHorizontalGroup(
            timestamp23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timestamp23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel38)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        timestamp23Layout.setVerticalGroup(
            timestamp23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timestamp23Layout.createSequentialGroup()
                .addComponent(jLabel38)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        timestampPanel.add(timestamp23);

        calendarPanel.add(timestampPanel);

        mondayPanel.setBackground(new java.awt.Color(240, 240, 200));
        mondayPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mondayPanel.setLayout(null);
        calendarPanel.add(mondayPanel);

        tuesdayPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tuesdayPanel.setLayout(null);
        calendarPanel.add(tuesdayPanel);

        wednesdayPanel.setBackground(new java.awt.Color(240, 240, 200));
        wednesdayPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        wednesdayPanel.setLayout(null);
        calendarPanel.add(wednesdayPanel);

        thursdayPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        thursdayPanel.setLayout(null);
        calendarPanel.add(thursdayPanel);

        fridayPanel.setBackground(new java.awt.Color(240, 240, 200));
        fridayPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fridayPanel.setLayout(null);
        calendarPanel.add(fridayPanel);

        saturdayPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        saturdayPanel.setLayout(null);
        calendarPanel.add(saturdayPanel);

        sundayPanel.setBackground(new java.awt.Color(240, 240, 200));
        sundayPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sundayPanel.setLayout(null);
        calendarPanel.add(sundayPanel);

        calendarScrollPane.setViewportView(calendarPanel);

        dayAndDatePanel.setMaximumSize(new java.awt.Dimension(861, 157));
        dayAndDatePanel.setMinimumSize(new java.awt.Dimension(0, 0));
        dayAndDatePanel.setLayout(new java.awt.GridLayout(1, 0));

        fillerPanel.setBackground(new java.awt.Color(230, 230, 230));

        javax.swing.GroupLayout fillerPanelLayout = new javax.swing.GroupLayout(fillerPanel);
        fillerPanel.setLayout(fillerPanelLayout);
        fillerPanelLayout.setHorizontalGroup(
            fillerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        fillerPanelLayout.setVerticalGroup(
            fillerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        dayAndDatePanel.add(fillerPanel);

        jPanel11.setBackground(new java.awt.Color(240, 240, 200));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Monday");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("99");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8))
                .addContainerGap())
        );

        dayAndDatePanel.add(jPanel11);

        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Tuesday");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("99");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9))
                .addContainerGap())
        );

        dayAndDatePanel.add(jPanel12);

        jPanel14.setBackground(new java.awt.Color(240, 240, 200));
        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText("Wednesday");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("99");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel10))
                .addContainerGap())
        );

        dayAndDatePanel.add(jPanel14);

        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setText("Thursday");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("99");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel11))
                .addContainerGap())
        );

        dayAndDatePanel.add(jPanel15);

        jPanel13.setBackground(new java.awt.Color(240, 240, 200));
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setText("Friday");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("99");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel12))
                .addContainerGap())
        );

        dayAndDatePanel.add(jPanel13);

        jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setText("Saturday");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("99");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel13))
                .addContainerGap())
        );

        dayAndDatePanel.add(jPanel17);

        jPanel16.setBackground(new java.awt.Color(240, 240, 200));
        jPanel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setText("Sunday");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("99");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel14))
                .addContainerGap())
        );

        dayAndDatePanel.add(jPanel16);

        informationPanel.setPreferredSize(new java.awt.Dimension(849, 267));

        needSpace.setBackground(new java.awt.Color(230, 230, 230));

        javax.swing.GroupLayout needSpaceLayout = new javax.swing.GroupLayout(needSpace);
        needSpace.setLayout(needSpaceLayout);
        needSpaceLayout.setHorizontalGroup(
            needSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        needSpaceLayout.setVerticalGroup(
            needSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout centerPanelLayout = new javax.swing.GroupLayout(centerPanel);
        centerPanel.setLayout(centerPanelLayout);
        centerPanelLayout.setHorizontalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(informationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(calendarScrollPane)
                    .addGroup(centerPanelLayout.createSequentialGroup()
                        .addComponent(dayAndDatePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(needSpace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        centerPanelLayout.setVerticalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dayAndDatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(needSpace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calendarScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(informationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(centerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(centerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * The method used to disconnect from the server and return the user to the login window.
     */
    private void logout() {
        main.logout();
        dispose();
        new Login(new Main()).setVisible(true);
    }
    
    public ArrayList<Room> getAllRooms() {
        //return main.getAllRooms();
        // TODO Get all rooms from server
        ArrayList<Room> temp = new ArrayList<>();
        temp.add(new Room(0, 5, "Room 1"));
        temp.add(new Room(1, 5, "Room 2"));
        temp.add(new Room(2, 5, "Room 3"));
        Room rom = new Room(3, 9, "fskmisvpmd");
        Meeting haxx = new Meeting(0, new Time(new Date().getTime()), new Time(new Date().getTime()+999999), "", null, null, null, null);
        rom.addAppointment(haxx);
        temp.add(rom);
        
        return temp;
    }
    public String getEmail() {
        return main.getEmail();
    }
    public Meeting getMeeting(int id) {
        return main.getMeeting(id);
    }
    public void addNotification(Notification not) {
        notifications.addElement(not);
    }
    
    private void populateWeekSelectionModel() {
        for (int i=1;i<=maximumWeek;i++) {
            weekSelectionModel.addElement(i);
        }
    }
    
    private void setWeek(int week) {
        currentWeek = week;
        weekNumberLabel.setText(week+"");
        hideInformationPanel();
        removeAllAppointments();
        updateDates();
        main.setCurrentWeek(week);
    }
    private void updateDates() {
    	currentCalendar.set(Calendar.WEEK_OF_YEAR, currentWeek);
    	currentCalendar.set(Calendar.DAY_OF_WEEK, Calendar.MONDAY);
    	jLabel8.setText(currentCalendar.getTime().toString().substring(4,10));
    	currentCalendar.set(Calendar.DAY_OF_WEEK, Calendar.TUESDAY);
    	jLabel9.setText(currentCalendar.getTime().toString().substring(4,10));
    	currentCalendar.set(Calendar.DAY_OF_WEEK, Calendar.WEDNESDAY);
    	jLabel10.setText(currentCalendar.getTime().toString().substring(4,10));
    	currentCalendar.set(Calendar.DAY_OF_WEEK, Calendar.THURSDAY);
    	jLabel11.setText(currentCalendar.getTime().toString().substring(4,10));
    	currentCalendar.set(Calendar.DAY_OF_WEEK, Calendar.FRIDAY);
    	jLabel12.setText(currentCalendar.getTime().toString().substring(4,10));
    	currentCalendar.set(Calendar.DAY_OF_WEEK, Calendar.SATURDAY);
    	jLabel13.setText(currentCalendar.getTime().toString().substring(4,10));
    	currentCalendar.set(Calendar.DAY_OF_WEEK, Calendar.SUNDAY);
    	jLabel14.setText(currentCalendar.getTime().toString().substring(4,10));
    }
    /**
     * Method used by the main program to fire alarms
     * @param alarm 
     */
    public void fireAlarm(Alarm alarm) {
        JOptionPane.showMessageDialog(this, alarm.getMessage(),"Alarm", JOptionPane.INFORMATION_MESSAGE);
    }
    public ArrayList<ListUnit> getAllInvitable() {
        // TODO Make this get the list from the server
        ArrayList<ListUnit> notInvited = new ArrayList<>();
        //FOR TESTING
        notInvited.add(new ListUnit("Tobias", "Tobias"));
        notInvited.add(new ListUnit("Tor","Tor"));
        notInvited.add(new ListUnit("Tore","Tore"));
        notInvited.add(new ListUnit("Jarle","Jarle"));
        notInvited.add(new ListUnit("Endre","Endre"));
        //END FOR TESTING
        return notInvited;
    }
    public Person getPersonByEmail(String email) {
        return main.getPersonByEmail(email);
    }
    public Group getGroupById(int id) {
        return main.getGroupById(id);
    }
    /**
     * Method to add appointments to the calendar view
     * @param model 
     */
    public void newAppointment(Meeting model) {
        System.out.println("newAppointment");
        main.newAppointment(model);
    }
    
    public void editAppointment(Meeting model) {
        main.editAppointment(model);
    }
    private void removeAllAppointments() {
        for (JPanel day : dayPanels) {
            day.removeAll();
        }
        revalidate();
        repaint();
    }
    public void deleteAppointment(Meeting app) {
        for (AppointmentView av : appointments) {
            if (av.getModel().equals(app)) {
                for (JPanel day : dayPanels) {
                    day.remove(av);
                }
            }
        }
        main.removeAppointment(app);
    }
    public void addAppointment(Meeting model) {
        //Creating a new appointment panel
        System.out.println("addAppointment");
        AppointmentView av = new AppointmentView(this, model);
        System.out.println("");
        appointments.add(av);
        System.out.println();
        //Getting the right day-panel to add the appointment to
        switch (Converters.dayStringFormat(model.getStart())) {
            case "Monday":
                mondayPanel.add(av);
                break;
            case "Tuesday":
                tuesdayPanel.add(av);
                break;
            case  "Wednesday":
                wednesdayPanel.add(av);
                break;
            case  "Thursday":
                thursdayPanel.add(av);
                break;
            case  "Friday":
                fridayPanel.add(av);
                break;
            case  "Saturday":
                saturdayPanel.add(av);
                break;
            case  "Sunday":
                sundayPanel.add(av);
                break;
            default:
        }
        revalidate();
        repaint();
    }
    /**
     * Showing the information panel with a new model
     * @param model 
     */
    public void showInformationPanel(Meeting model) {
        informationPanel.setModel(model);
        informationPanel.hideConfirmation();
        informationPanel.setVisible(true);
    }
    /**
     * Hiding the information table
     */
    public void hideInformationPanel() {
        informationPanel.setVisible(false);
    }
    private void newAppointmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAppointmentButtonActionPerformed
        new AppointmentEditor(this).setVisible(true);
    }//GEN-LAST:event_newAppointmentButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        logout();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void calendarScrollPaneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calendarScrollPaneMousePressed
        hideInformationPanel();
    }//GEN-LAST:event_calendarScrollPaneMousePressed

    private void calendarScrollPaneMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calendarScrollPaneMouseReleased
        revalidate();
    }//GEN-LAST:event_calendarScrollPaneMouseReleased

    private void skipToWeekBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skipToWeekBoxActionPerformed
        setWeek((int)skipToWeekBox.getSelectedItem());
    }//GEN-LAST:event_skipToWeekBoxActionPerformed

    private void nextWeekButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextWeekButtonActionPerformed
        if ((int)weekSelectionModel.getSelectedItem() != maximumWeek) {
            weekSelectionModel.setSelectedItem((int)weekSelectionModel.getSelectedItem() + 1);
        }
    }//GEN-LAST:event_nextWeekButtonActionPerformed

    private void previousWeekButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousWeekButtonActionPerformed
        if ((int)weekSelectionModel.getSelectedItem() != 1) {
            weekSelectionModel.setSelectedItem((int)weekSelectionModel.getSelectedItem() - 1);
        }
    }//GEN-LAST:event_previousWeekButtonActionPerformed

    private void notificationListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_notificationListValueChanged
        showInformationPanel(main.getMeeting(notifications.getElementAt(notificationList.getSelectedIndex()).getAppID()));
    }//GEN-LAST:event_notificationListValueChanged
    // END NetBeans event handlers.
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addOtherPersonButton;
    private javax.swing.JPanel calendarPanel;
    private javax.swing.JScrollPane calendarScrollPane;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JPanel dayAndDatePanel;
    private javax.swing.JPanel fillerPanel;
    private javax.swing.JPanel fridayPanel;
    private gui.InformationPanel informationPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JPanel mondayPanel;
    private javax.swing.JPanel needSpace;
    private javax.swing.JButton newAppointmentButton;
    private javax.swing.JButton nextWeekButton;
    private javax.swing.JList notificationList;
    private javax.swing.JScrollPane notificationScroll;
    private javax.swing.JLabel notificationsLable;
    private javax.swing.JLabel otherCalendarLabel;
    private javax.swing.JComboBox otherPersonBox;
    private javax.swing.JButton previousWeekButton;
    private javax.swing.JPanel saturdayPanel;
    private javax.swing.JSeparator separator1;
    private javax.swing.JSeparator separator2;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JComboBox skipToWeekBox;
    private javax.swing.JLabel skipToWeekLabel;
    private javax.swing.JPanel sundayPanel;
    private javax.swing.JPanel thursdayPanel;
    private javax.swing.JPanel timestamp0;
    private javax.swing.JPanel timestamp1;
    private javax.swing.JPanel timestamp10;
    private javax.swing.JPanel timestamp11;
    private javax.swing.JPanel timestamp12;
    private javax.swing.JPanel timestamp13;
    private javax.swing.JPanel timestamp14;
    private javax.swing.JPanel timestamp15;
    private javax.swing.JPanel timestamp16;
    private javax.swing.JPanel timestamp17;
    private javax.swing.JPanel timestamp18;
    private javax.swing.JPanel timestamp19;
    private javax.swing.JPanel timestamp2;
    private javax.swing.JPanel timestamp20;
    private javax.swing.JPanel timestamp21;
    private javax.swing.JPanel timestamp22;
    private javax.swing.JPanel timestamp23;
    private javax.swing.JPanel timestamp3;
    private javax.swing.JPanel timestamp4;
    private javax.swing.JPanel timestamp5;
    private javax.swing.JPanel timestamp6;
    private javax.swing.JPanel timestamp7;
    private javax.swing.JPanel timestamp8;
    private javax.swing.JPanel timestamp9;
    private javax.swing.JPanel timestampPanel;
    private javax.swing.JPanel topPanel;
    private javax.swing.JPanel tuesdayPanel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JPanel wednesdayPanel;
    private javax.swing.JLabel weekLabel;
    private javax.swing.JLabel weekNumberLabel;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
